Audio/background player for downloads
libre-tube/LibreTube pull request #3525
Opened 2023-04-10 13:54 UTC by Bnyro

2023-04-10 23:54 UTC, Isira-Seneviratne requested changes
Overall, this looks good to me. I've suggested a couple of small changes.

2023-04-10 23:54 UTC, Isira-Seneviratne commented on app/src/main/java/com/github/libretube/services/OfflinePlayerService.kt
> +class OfflinePlayerService : Service() {
```suggestion
class OfflinePlayerService : LifecycleService() {
```

2023-04-10 23:54 UTC, Isira-Seneviratne commented on app/src/main/java/com/github/libretube/services/OfflinePlayerService.kt
> +        CoroutineScope(Dispatchers.IO).launch {
```suggestion
        lifecycleScope.launch(Dispatchers.IO) {
```

2023-04-11 07:53 UTC, merged

2023-04-15 13:28 UTC, mxwmnn commented
Works partially, you can't skip songs it only plays one audio and doesn't have continuous play. Would be nice. Thanks for the effort guys