fix: false message about no comments and btnTop scroll
libre-tube/LibreTube pull request #5726
Opened 2024-03-11 18:58 UTC by nik-conder

In new versions (not yet released), comments are broken. Including responses to comments. 
I tried to fix btn Top and corrected the false text output that there are no comments when in fact there are. I haven't figured out the reason yet, so the code may need to be adjusted or supplemented.

2024-03-12 01:00 UTC, Isira-Seneviratne requested changes
Looks good to me overall, thanks for the comment fix. I've suggested a couple of small changes.

2024-03-12 01:00 UTC, Isira-Seneviratne commented on app/src/main/java/com/github/libretube/ui/fragments/CommentsRepliesFragment.kt
> +        const val POSITION_START = 0
```suggestion
        private const val POSITION_START = 0
```

2024-03-12 02:20 UTC, nik-conder commented
Sorry, the following commit accidentally flew in here, which does not relate to the previous fix. Isn't that scary?

2024-03-17 12:00 UTC, closed without merging

2024-03-17 12:01 UTC, Bnyro commented
Merged in https://github.com/libre-tube/LibreTube/pull/5751, thanks!

Please don't merge the LibreTube master branch into yours next time and don't disable that others can push your branch.

2024-03-17 17:41 UTC, nik-conder commented
@Bnyro Thank you very much. Sorry again, I'm just learning.

> Please don't merge the LibreTube master branch into yours next time

Please specify what is meant here?