fix: default quality setting should respect video aspect ratio
libre-tube/LibreTube pull request #5797
Opened 2024-03-23 15:50 UTC by manish99verma

2024-03-24 23:26 UTC, Bnyro requested changes
When autoplay continues and the next video is a short again, the factor will be `(16/9)^2` after your changes.
And when the next video is a normal one and not a short, it still uses the resolution for shorts.

TLDR: Your code shouldn't change the `fullscreenOrientation` variables, it should only read them in the function where the resolution is set and set it to `16/9 * resolution` ditectly instead of modifying the variable.

2024-03-28 10:20 UTC, manish99verma commented
Now it will set resolution directly without modifing the default variables and when user will change resoultion for Shorts, let say to 1280 then it will save 720 as a default resoultion for current queue.

2024-03-28 14:16 UTC, Bnyro commented
I think it would be better to do this in `setPlayerResolution` instead of at 3 different places.

2024-03-28 15:05 UTC, manish99verma commented
That would work. But, i think it will create some problem when user will select a custom resolution while playing a video. So we can pass a boolean to setPlayerResolution whether it is choosed by user or it's default.

2024-03-28 15:08 UTC, Bnyro commented
> That would work. But, i think it will create some problem when user will select a custom resolution while playing a video. So we can pass a boolean to setPlayerResolution whether it is choosed by user or it's default.
>
Yes, sounds good :+1:

2024-03-28 16:40 UTC, Bnyro commented on app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
> +        }
```suggestion
        val transformedResolution = if (!isSelectedByUser && isShort) {
            ceil(resolution * 16.0 / 9.0).toInt()
        } else {
            resolution
        }
```

2024-03-28 16:41 UTC, Bnyro commented on app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
> +                }
I think this code here should be removed, since we already handle that in `setPlayerResolution`?

2024-04-01 18:22 UTC, Bnyro commented on app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
> +    private fun setPlayerResolution(resolution: Int, isSelectedByUser: Boolean) {
```suggestion
    private fun setPlayerResolution(resolution: Int, isSelectedByUser: Boolean = false) {
```
simplifies things.

2024-04-01 18:26 UTC, Bnyro commented on app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
> +                }
I don't really like/agree on this change, it's not a good idea to modify the `newResolution` variable, it should always be in the "same format" (normal horizontal video ratio resolution).

2024-04-01 18:27 UTC, Bnyro commented on app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
> +                }
This here makes everything more complicated and I don't think anybody knows what's going on when maintaining that code in the future.

2024-04-01 18:27 UTC, Bnyro commented on app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
>                  // save the selected resolution to update on fullscreen change
the comment should be moved below where the actual resolution update code is.

2024-04-17 17:25 UTC, Bnyro approved these changes

2024-04-17 17:27 UTC, merged