Retain exoplayer on orientation change
libre-tube/LibreTube pull request #6428
Opened 2024-08-31 13:15 UTC by Pittvandewitt

This PR is basically the last step of https://github.com/libre-tube/LibreTube/pull/6307
Now you should feel the improvement upon rotation change ;)

The ExoPlayer is no longer stopped on onDestroy, because it is already released in its viewmodel onDestroy method.

2024-09-03 16:17 UTC, Bnyro approved these changes

2024-09-03 16:20 UTC, Bnyro requested changes
Wait, this would also mean that the current player video stays alive when the user closes a video and it still continues to buffer.

Apart from that `viewModel.isOrientationChange` already conditionally does what you're trying to achieve with this PR, doesn't it?

2024-09-04 07:57 UTC, Pittvandewitt commented
When the video closes with `PlayerFragment`, `PlayerViewModel` is also destroyed and `PlayerViewModel.onCleared` is called, where the exoplayer is released. Or does `ExoPlayer.stop` also need to be called before `ExoPlayer.release`?

With this PR I notice no interruption when changing orientation, but with the current implementation of `viewModel.isOrientationChange` I always do, especially when pressing the full screen button.

2024-09-05 09:01 UTC, Bnyro commented
> When the video closes with PlayerFragment, PlayerViewModel is also destroyed and PlayerViewModel.onCleared is called,
>
You're right, I thought that would only be called in the activity's `onDestroy` and not in the fragments, but I tested it and it looks like you're right.

2024-09-05 09:01 UTC, Bnyro approved these changes

2024-09-05 09:01 UTC, merged